### ISSUE TITLE
This installs Symfony 5 when the tutorial is for Symfony 3

### ISSUE THREAD

**Issue by givihuda** [billythakidd04/aqua_note#1]
I'm not sure how to fix this. Symfony 5 is very different from Symfony 3. I found this from tutorial SymfonyCasts tutorial 'Joyful Development with Symfony 3' https://symfonycasts.com/screencast/symfony3/start-project

Please advise. I'm not seeing how to target versioning properly for this. I ran CLI command `symfony new aqua_note`.

I'm ultimately trying to learn Symfony 3 better for an upgrade of a repo, on an unfortunate hybrid of Symfony 2 and 3, to 6 eventually, and trying to learn Symfony 3 well enough in the meantime.

**Comment by billythakidd04** [comment]
This is not meant to be a tutorial repo but I can try to help. This was just where I stored my stuff as I went through a tutorial myself. The symfony version is targeted based on the composer file.

**Comment by givihuda** [comment]
Here's the issue:

Going through your README.md instructions installs Symfony 5 when the "tutorial" (the KnpUniversity course?) is for Symfony 3.

See, I just called your "course" a "tutorial" because the page I got this repo from was the "course" in the SymfonyCasts link I provided in my original post, which calls itself a "tutorial" in at least one place (see screenshot below, or visit the link in Incognito or while logged out):

![image](https://user-images.githubusercontent.com/74785256/173384268-0acd67b1-8fbb-4957-9b64-d2ee764ce863.png)

It says near the top highlighted in orange: "This **tutorial** has a new version, check it out!" (link - https://symfonycasts.com/screencast/symfony4 - though where it links to is not the point)

Do you see where I'm coming from?

That "tutorial" (course?) mentions to install aqua_note:

> Downloading the Project
> Let's start one! Run symfony new and then the name of the project. Call the project aqua_note:
> 
> symfony new aqua_note

Doing a Google search for symfony aqua_note shows this repo:

![image](https://user-images.githubusercontent.com/74785256/173383758-baa30da2-7718-48b6-84ec-c30b15ad5b9a.png)

So what's going on? Is this repo not the correct one used? 

Sure, I can change my composer file to target a certain Symfony version, but I'm confused on your connection to that tutorial/course. Is this repo just some personal forked/copied upload and the original repo doesn't exist anymore?

**Comment by billythakidd04** [comment]
I cant speak to the original repo and it's almost funny that mine is the first result but yeah, I have no connection to knp or symfony other than I tinkered with it and forked it for myself. In fact I really should delete this repo if it's coming up on google.

**Comment by givihuda** [comment]
Thanks for clarifying.
